name: belajar_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 
  dio: ^5.9.0
  http: ^1.5.0
  intl: ^0.20.2

  # 
  provider: ^6.1.5+1

  # 
  flutter_html: ^3.0.0

  # 
  youtube_player_iframe: ^5.2.2
  visibility_detector: ^0.4.0+2
  from_css_color: ^2.0.0

  # 
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
